"""create workflow table

Revision ID: aba374915d62
Revises: 5d6dee120c48
Create Date: 2025-09-01 13:44:01.570109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba374915d62'
down_revision: Union[str, None] = '5d6dee120c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_assistant_id'), 'workflows', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflows_thread_id'), 'workflows', ['thread_id'], unique=False)
    op.create_index(op.f('ix_workflows_workflow_id'), 'workflows', ['workflow_id'], unique=False)
    
    # Clear existing data to avoid conversion issues (safe for development)
    op.execute('TRUNCATE TABLE threads CASCADE')
    
    # Safe UUID conversion with USING clause
    op.execute('ALTER TABLE threads ALTER COLUMN thread_id TYPE UUID USING thread_id::UUID')
    op.execute('ALTER TABLE threads ALTER COLUMN tenant_id TYPE UUID USING tenant_id::UUID') 
    op.execute('ALTER TABLE threads ALTER COLUMN assistant_id TYPE UUID USING assistant_id::UUID')
    op.alter_column('threads', 'assistant_id', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('threads', 'assistant_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('threads', 'thread_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_workflows_workflow_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_thread_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_assistant_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###



