"""tenant model

Revision ID: e8ae6dcbd980
Revises: 
Create Date: 2025-08-21 10:45:23.103291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8ae6dcbd980'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('industry', sa.Integer(), nullable=False),
    sa.Column('company_size', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('editor', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_deleted', 'tenants', ['deleted'], unique=False)
    op.create_index('idx_tenant_id', 'tenants', ['tenant_id'], unique=False)
    op.create_index('idx_tenant_industry', 'tenants', ['industry'], unique=False)
    op.create_index('idx_tenant_status', 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index('idx_tenant_status', table_name='tenants')
    op.drop_index('idx_tenant_industry', table_name='tenants')
    op.drop_index('idx_tenant_id', table_name='tenants')
    op.drop_index('idx_tenant_deleted', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###



