"""add trigger and takeover field in thread

Revision ID: 465ece714a65
Revises: 4cb1fb0abd4d
Create Date: 2026-01-12 12:09:10.208252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465ece714a65'
down_revision: Union[str, None] = '4cb1fb0abd4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 server_default 为现有行提供默认值
    op.add_column('threads', sa.Column('enable_trigger', sa.Boolean(), nullable=False, server_default=sa.false(), comment='是否允许主动触发'))
    op.add_column('threads', sa.Column('enable_takeover', sa.Boolean(), nullable=False, server_default=sa.true(), comment='是否允许AI接管'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'enable_takeover')
    op.drop_column('threads', 'enable_trigger')
    # ### end Alembic commands ###



