"""rename field in thread model

Revision ID: 4cb1fb0abd4d
Revises: b113bcd869ef
Create Date: 2025-12-26 15:20:35.300824

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4cb1fb0abd4d'
down_revision: Union[str, None] = 'b113bcd869ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'last_awakening_at', new_column_name='last_interaction_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'last_interaction_at', new_column_name='last_awakening_at')
    # ### end Alembic commands ###



