"""refactor tenant model

Revision ID: 538534b1c469
Revises: e651c56a5502
Create Date: 2025-11-30 20:48:45.699187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '538534b1c469'
down_revision: Union[str, None] = 'e651c56a5502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'industry',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('tenants', 'area_id')
    op.drop_column('tenants', 'features')
    op.drop_column('tenants', 'user_count')
    op.drop_column('tenants', 'expires_at')
    op.drop_column('tenants', 'editor')
    op.drop_column('tenants', 'company_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('company_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('editor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('user_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('area_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('tenants', 'industry',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###



