"""modify data model

Revision ID: 6ee06edc35dd
Revises: 
Create Date: 2025-09-18 16:22:22.529242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ee06edc35dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'CLOSED', name='tenant_status'), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('company_size', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.String(length=64), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('editor', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index('idx_tenant_industry', 'tenants', ['industry'], unique=False)
    op.create_index('idx_tenant_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index('idx_tenant_status', 'tenants', ['status'], unique=False)
    op.create_table('threads',
    sa.Column('thread_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assistant_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PROCESSING', 'IDLE', 'FAILED', 'PAUSED', 'DELETED', name='thread_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_threads_assistant_id'), 'threads', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_threads_status'), 'threads', ['status'], unique=False)
    op.create_index(op.f('ix_threads_tenant_id'), 'threads', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('assistant_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index(op.f('ix_workflows_assistant_id'), 'workflows', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflows_thread_id'), 'workflows', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_thread_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_assistant_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_threads_tenant_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_status'), table_name='threads')
    op.drop_index(op.f('ix_threads_assistant_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index('idx_tenant_status', table_name='tenants')
    op.drop_index('idx_tenant_is_active', table_name='tenants')
    op.drop_index('idx_tenant_industry', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###



