"""update fields to threads

Revision ID: 9ba9ae9b6e69
Revises: a2d91ce1b181
Create Date: 2025-12-10 16:41:04.416852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba9ae9b6e69'
down_revision: Union[str, None] = 'a2d91ce1b181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('services', sa.ARRAY(sa.String()), nullable=True, comment='客户已消费的服务列表'))
    op.add_column('threads', sa.Column('is_converted', sa.Boolean(), nullable=True, comment='客户是否已转化（已消费）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'is_converted')
    op.drop_column('threads', 'services')
    # ### end Alembic commands ###



