"""create new migration files

Revision ID: b113bcd869ef
Revises: 
Create Date: 2025-12-23 12:30:52.824248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b113bcd869ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant',
    sa.Column('assistant_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('assistant_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'CLOSED', name='account_status'), nullable=False),
    sa.Column('personality', sa.String(length=500), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('voice_file', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('assistant_id')
    )
    op.create_index('idx_assistant_is_active', 'assistant', ['is_active'], unique=False)
    op.create_index('idx_assistant_status', 'assistant', ['status'], unique=False)
    op.create_index('idx_assistant_updated', 'assistant', ['updated_at'], unique=False)
    op.create_index(op.f('ix_assistant_tenant_id'), 'assistant', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'CLOSED', name='account_status'), nullable=False),
    sa.Column('industry', sa.String(length=500), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index('idx_tenant_industry', 'tenants', ['industry'], unique=False)
    op.create_index('idx_tenant_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index('idx_tenant_status', 'tenants', ['status'], unique=False)
    op.create_table('threads',
    sa.Column('thread_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('assistant_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'ACTIVE', 'BUSY', 'FAILED', name='thread_status'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True, comment='客户姓名'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='客户昵称'),
    sa.Column('real_name', sa.String(length=128), nullable=True, comment='客户真实姓名'),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=True, comment='客户性别'),
    sa.Column('age', sa.Integer(), nullable=True, comment='客户年龄'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='客户电话'),
    sa.Column('occupation', sa.String(length=128), nullable=True, comment='客户职业'),
    sa.Column('services', sa.ARRAY(sa.String()), nullable=True, comment='客户已消费的服务列表'),
    sa.Column('is_converted', sa.Boolean(), nullable=False, comment='客户是否已转化（已消费）'),
    sa.Column('awakening_attempt_count', sa.Integer(), nullable=False, comment='唤醒消息发送次数'),
    sa.Column('last_awakening_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次互动时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_threads_assistant_id'), 'threads', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_threads_phone'), 'threads', ['phone'], unique=False)
    op.create_index(op.f('ix_threads_status'), 'threads', ['status'], unique=False)
    op.create_index(op.f('ix_threads_tenant_id'), 'threads', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('assistant_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index(op.f('ix_workflows_assistant_id'), 'workflows', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflows_thread_id'), 'workflows', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_thread_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_assistant_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_threads_tenant_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_status'), table_name='threads')
    op.drop_index(op.f('ix_threads_phone'), table_name='threads')
    op.drop_index(op.f('ix_threads_assistant_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index('idx_tenant_status', table_name='tenants')
    op.drop_index('idx_tenant_is_active', table_name='tenants')
    op.drop_index('idx_tenant_industry', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_assistant_tenant_id'), table_name='assistant')
    op.drop_index('idx_assistant_updated', table_name='assistant')
    op.drop_index('idx_assistant_status', table_name='assistant')
    op.drop_index('idx_assistant_is_active', table_name='assistant')
    op.drop_table('assistant')
    # ### end Alembic commands ###



