"""add_awakening_fields_to_threads

Revision ID: d626cdaef8ee
Revises: f8972c79f2ae
Create Date: 2025-12-19 17:10:32.662782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd626cdaef8ee'
down_revision: Union[str, None] = 'f8972c79f2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('awakening_attempt_count', sa.Integer(), nullable=False, comment='唤醒消息发送次数'))
    op.add_column('threads', sa.Column('last_awakening_sent_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次唤醒消息发送时间'))
    op.alter_column('threads', 'is_converted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='客户是否已转化（已消费）')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'is_converted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='客户是否已转化（已消费）')
    op.drop_column('threads', 'last_awakening_sent_at')
    op.drop_column('threads', 'awakening_attempt_count')
    # ### end Alembic commands ###



