"""rename assistant fields

Revision ID: e651c56a5502
Revises: 6ee06edc35dd
Create Date: 2025-11-25 22:54:52.740059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e651c56a5502'
down_revision: Union[str, None] = '6ee06edc35dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant',
    sa.Column('assistant_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('assistant_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'CLOSED', name='account_status', create_type=False), nullable=False),
    sa.Column('personality', sa.String(length=500), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('voice_file', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('assistant_id')
    )
    op.create_index('idx_assistant_is_active', 'assistant', ['is_active'], unique=False)
    op.create_index('idx_assistant_status', 'assistant', ['status'], unique=False)
    op.create_index('idx_assistant_updated', 'assistant', ['updated_at'], unique=False)
    op.create_index(op.f('ix_assistant_tenant_id'), 'assistant', ['tenant_id'], unique=False)

    # 更新 tenants 表的 status 列使用新的枚举类型
    op.execute("ALTER TABLE tenants ALTER COLUMN status TYPE account_status USING status::text::account_status")
    op.execute("DROP TYPE IF EXISTS tenant_status")

    op.alter_column('workflows', 'tenant_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'tenant_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('ACTIVE', 'BANNED', 'CLOSED', name='account_status'),
               type_=postgresql.ENUM('ACTIVE', 'BANNED', 'CLOSED', name='tenant_status'),
               existing_nullable=False)
    op.drop_index(op.f('ix_assistant_tenant_id'), table_name='assistant')
    op.drop_index('idx_assistant_updated', table_name='assistant')
    op.drop_index('idx_assistant_status', table_name='assistant')
    op.drop_index('idx_assistant_is_active', table_name='assistant')
    op.drop_table('assistant')
    # ### end Alembic commands ###



