"""add nickname and real_name to threads

Revision ID: f8972c79f2ae
Revises: 9ba9ae9b6e69
Create Date: 2025-12-11 15:21:53.324048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8972c79f2ae'
down_revision: Union[str, None] = '9ba9ae9b6e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('nickname', sa.String(length=128), nullable=True, comment='客户昵称'))
    op.add_column('threads', sa.Column('real_name', sa.String(length=128), nullable=True, comment='客户真实姓名'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'real_name')
    op.drop_column('threads', 'nickname')
    # ### end Alembic commands ###



